apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-deployment
spec:
  selector:
    matchLabels:
      app: py
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: py
    spec:
      containers:
      - name: py
        image: kishorja/pythonproject
        ports:
        - containerPort: 80
